#+TITLE: Show Gravatar

*Show Gravatar* is a plugin for [[https://roundcube.net/][Roundcube webmail]], which displays the e-mail
sender's [[https://gravatar.com/][Gravatar]] in every message and in the address book.

Manually assigned photos in the address book have a higher priority. For contacts where
no manual photo or Gravatar exists, the default Gravatar type is displayed. You can
select the default Gravatar type in your user settings, as well as the minimum [[https://en.gravatar.com/site/implement/images/#rating][audience rating]].

*Gravatar types:*
- *mp:* (Mystery Person) a simple, cartoon-style silhouetted outline of a person
- *identicon:* a geometric pattern based on an email hash
- *monsterid:* a generated monster with different colors and faces
- *wavatar:* generated faces with differing features and backgrounds
- *retro:* generated, 8-bit arcade-style pixelated faces
- *robohash:* a generated robot with different colors, faces, etc

In Roundcube's ~config.inc.php~ file, you can replace the plugin's default Gravatar type ('mp') and minimum rating ('g') for anyone
that hasn't yet selected them in their settings and for new accounts:

#+begin_src php
// show_gravatar plugin
$config['gravatar_default'] = 'identicon';
$config['gravatar_rating'] = 'r';
#+end_src

* Installation

From the RoundCube ~plugins~ directory, type

#+begin_src sh
git clone git://github.com/kepi/show-gravatar.git show_gravatar
#+end_src

* License
This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a [[./LICENSE.org][copy of the GNU General Public License]] along with
this program. If not, see <https://www.gnu.org/licenses/>.
