#+TITLE: Show Gravatar

*Show Gravatar* is [[https://roundcube.net/][Roundcube webmail client]] plugin which displays e-mail
sender's [[https://gravatar.com/][Gravatar]] in every message and in address book.

Manually assigned photo in address book has higher priority. For contacts where
no manual photo or Gravatar exists default gravatar type is displayed. You can
adjust default Gravatar type in settings as well as minimum rating.

* Instalation

From your RoundCube plugins directory type

#+begin_src sh
git clone git://github.com/kepi/show-gravatar.git show_gravatar
#+end_src

* License
This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a [[./LICENSE.org][copy of the GNU General Public License]] along with
this program. If not, see <https://www.gnu.org/licenses/>.
