<?php

/*

+-----------------------------------------------------------------------+
| Language/cs_CZ/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube show gravatar plugin                   |
| Copyright (C) 2005-2009, RoundCube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Ondra 'Kepi' Kudlik <kepi@igloonet.cz>                        |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['gravatars']  = 'Gravatary';
$labels['gravatar_enable_message']  = 'Povolit v detailu zprávy';
$labels['gravatar_enable_preview']  = 'Povolit v náhledu zprávy';

?>
