<?php

/*

+-----------------------------------------------------------------------+
|                                                                       |
| Language file of the RoundCube show gravatar plugin                   |
| Copyright (C) 2005-2009, RoundCube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Ondra 'Kepi' Kudlik <kepi@igloonet.cz>                        |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['gravatars']  = 'Gravatary';
$labels['gravatar_enable_message']  = 'Povolit v detailu zprávy';
$labels['gravatar_enable_preview']  = 'Povolit v náhledu zprávy';
$labels['gravatar_size'] = 'Velikost avataru';
$labels['gravatar_rating'] = 'Hodnocení avataru';
$labels['gravatar_default'] = 'Výchozí avatar, pokud uživatel nemá';
$labels['gravatar_border'] = 'Rámeček kolem avataru';

?>
