<?php

/*
 +-----------------------------------------------------------------------+
 | localization/de_CH.inc                                                |
 |                                                                       |
| Language file of the RoundCube show gravatar plugin                    |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas Bruederli <thomas@roundcube.net>                       |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['gravatars']  = 'Gravatare';
$labels['gravatar_enable_message'] = 'In der Nachricht anzeigen'; 
$labels['gravatar_enable_preview'] = 'In der Vorschau anzeigen';
$labels['gravatar_size'] = 'Avatar Grösse';
$labels['gravatar_rating'] = 'Avatar Bewertung';
$labels['gravatar_default'] = 'Standard Avatar wenn kein Bild gefunden';
$labels['gravatar_border'] = 'Rahmen um Avatar';

?>
