<?php

/*
 +-----------------------------------------------------------------------+
 | localization/de_CH.inc                                                |
 |                                                                       |
| Language file of the RoundCube show gravatar plugin                    |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas Bruederli <thomas@roundcube.net>                       |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['gravatars'] = 'Gravatare';
$labels['gravatar_rating'] = 'Avatar Bewertung';
$labels['gravatar_default'] = 'Standard Avatar wenn kein Bild gefunden';
$labels['gravatar_G'] = 'G';
$labels['gravatar_PG'] = 'PG';
$labels['gravatar_R'] = 'R';
$labels['gravatar_X'] = 'X';
