<?php

/*

+-----------------------------------------------------------------------+
| Language/de_DE/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube show gravatar plugin                   |
| Copyright (C) 2005-2009, RoundCube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:  RogerSik <roger@sikorski.cc>                                 |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['gravatars'] = 'Gravatars'; 
$labels['gravatar_enable'] = 'In der Nachricht anzeigen'; 
$labels['gravatar_enable'] = 'In der Vorschau anzeigen';

?>
