<?php

/*

+-----------------------------------------------------------------------+
|                                                                       |
| Language file of the RoundCube show gravatar plugin                   |
| Copyright (C) 2005-2009, RoundCube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:  Roger 'RogerSik' Sikorski <roger@sikorski.cc>                |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['gravatars']  = 'Gravatare';
$labels['gravatar_enable_message'] = 'In der Nachricht anzeigen'; 
$labels['gravatar_enable_preview'] = 'In der Vorschau anzeigen';
$labels['gravatar_size'] = 'Avatar Größe';
$labels['gravatar_rating'] = 'Avatar Bewertung';
$labels['gravatar_default'] = 'Standard Avatar wenn Avatar fehlt';
$labels['gravatar_border'] = 'Avatar einrahmen';

?>
