<?php

/*

+-----------------------------------------------------------------------+
|                                                                       |
| Language file of the RoundCube show gravatar plugin                   |
| Copyright (C) 2005-2009, RoundCube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Ondra 'Kepi' Kudlik <kepi@igloonet.cz>                        |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['gravatars']  = 'Gravatars';
$labels['gravatar_enable_message']  = 'Show on message detail';
$labels['gravatar_enable_preview']  = 'Show on message preview';

?>
