<?php

/*

+-----------------------------------------------------------------------+
|                                                                       |
| Language file of the RoundCube show gravatar plugin                   |
| Copyright (C) 2005-2009, RoundCube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Ondra 'Kepi' Kudlik <kepi@igloonet.cz>                        |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['gravatars']  = 'Gravatars';
$labels['gravatar_enable_message']  = 'Show on message detail';
$labels['gravatar_enable_preview']  = 'Show on message preview';
$labels['gravatar_size'] = 'Avatar size';
$labels['gravatar_rating'] = 'Avatar rating';
$labels['gravatar_default'] = 'Default avatar if gravatar missing';
$labels['gravatar_border'] = 'Border around avatar';
$labels['gravatar_none'] = 'None';
$labels['gravatar_G'] = 'G rated';
$labels['gravatar_PG'] = 'PG rated';
$labels['gravatar_R'] = 'R rated';
$labels['gravatar_X'] = 'X rated';

?>
