<?php

/*

+-----------------------------------------------------------------------+
|                                                                       |
| Language file of the RoundCube show gravatar plugin                   |
| Copyright (C) 2005-2009, RoundCube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Ondra 'Kepi' Kudlik <kepi@igloonet.cz>                        |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['gravatars'] = 'Gravatar';
$labels['gravatar_rating'] = 'Puntuación del avatar';
$labels['gravatar_default'] = 'Avatar por defecto si no hay uno';
$labels['gravatar_G'] = 'G';
$labels['gravatar_PG'] = 'PG';
$labels['gravatar_R'] = 'R';
$labels['gravatar_X'] = 'X';
