<?php

/*

+-----------------------------------------------------------------------+
|                                                                       |
| Language file of the RoundCube show gravatar plugin                   |
| Copyright (C) 2005-2009, RoundCube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Lorenzo Salvadorini aka LoreLLo <lorello@openweb.it>          |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['gravatars'] = 'Gravatars';
$labels['gravatar_rating'] = 'Valutazione Avatar';
$labels['gravatar_default'] = 'Avatar predefinito in caso non sia impostato';
$labels['gravatar_G'] = 'G';
$labels['gravatar_PG'] = 'PG';
$labels['gravatar_R'] = 'R';
$labels['gravatar_X'] = 'X';
