<?php

/*

+-----------------------------------------------------------------------+
|                                                                       |
| Language file of the RoundCube show gravatar plugin                   |
| Copyright (C) 2005-2009, RoundCube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Lorenzo Salvadorini aka LoreLLo <lorello@openweb.it>          |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['gravatars']  = 'Gravatars';
$labels['gravatar_enable_message']  = 'Mostra nel dettaglio del messaggio';
$labels['gravatar_enable_preview']  = 'Mostra sull\'anterprima del messaggio';
$labels['gravatar_size'] = 'Dimensione dell\'Avatar';
$labels['gravatar_rating'] = 'Valutazione Avatar';
$labels['gravatar_default'] = 'Avatar predefinito in caso non sia impostato';
$labels['gravatar_border'] = 'Bordo attorno all\'Avatar';
$labels['gravatar_none'] = 'Nessuno';
$labels['gravatar_G'] = 'G';
$labels['gravatar_PG'] = 'PG';
$labels['gravatar_R'] = 'R';
$labels['gravatar_X'] = 'X';

?>

