<?php

/*

+-----------------------------------------------------------------------+
|                                                                       |
| Language file of the RoundCube show gravatar plugin                   |
| Copyright (C) 2005-2009, RoundCube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Kirill Miazine <km@krot.org>                                  |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['gravatars'] = 'Gravatar';
$labels['gravatar_G'] = 'G';
$labels['gravatar_PG'] = 'PG';
$labels['gravatar_R'] = 'R';
$labels['gravatar_X'] = 'X';
