<?php

/*

+-----------------------------------------------------------------------+
|                                                                       |
| Language file of the RoundCube show gravatar plugin                   |
| Copyright (C) 2005-2009, RoundCube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Kirill Miazine <km@krot.org>                                  |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['gravatars'] = 'Gravatar';
$labels['gravatar_enable_message'] = 'Vis Gravatar ved visning av melding';
$labels['gravatar_enable_preview'] = 'Vis Gravatar ved forhåndsvisning av melding';

?>
