<?php

/*

+-----------------------------------------------------------------------+
|                                                                       |
| Language file of the RoundCube show gravatar plugin                   |
| Copyright (C) 2005-2009, RoundCube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Kirill Miazine <km@krot.org>                                  |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['gravatars'] = 'Граватар';
$labels['gravatar_enable_message'] = 'Показывать граватар при чтении сообщения';
$labels['gravatar_enable_preview'] = 'Показывать граватар в превью сообщения';
$labels['gravatar_size'] = 'Размер аватара';
$labels['gravatar_rating'] = 'Рейтинг аватара';
$labels['gravatar_default'] = 'Аватар по умолчанию, если граватар отсутствует';
$labels['gravatar_border'] = 'Рамка вокруг аватара';
$labels['gravatar_none'] = 'Нет';
$labels['gravatar_G'] = 'Рейтинг G (любая аудитория)';
$labels['gravatar_PG'] = 'Рейтинг PG (неприличные жесты, провокационная одежда, грубые выражения или умеренная жестокость)';
$labels['gravatar_R'] = 'Рейтинг R (ненормативная лексика, сцены жестокости, обнаженные тела или употребление наркотиков)';
$labels['gravatar_X'] = 'Рейтинг X (откровенные сексуальные изображения или сцены экстремальной жестокости)';
